#  Hydrogram - Telegram MTProto API Client Library for Python
#  Copyright (C) 2023-present Hydrogram <https://hydrogram.org>
#
#  This file is part of Hydrogram.
#
#  Hydrogram is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as published
#  by the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Hydrogram is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with Hydrogram.  If not, see <http://www.gnu.org/licenses/>.

from io import BytesIO

from hydrogram.raw.core.primitives import Int, Long, Int128, Int256, Bool, Bytes, String, Double, Vector
from hydrogram.raw.core import TLObject
from hydrogram import raw
from typing import List, Optional, Any

# # # # # # # # # # # # # # # # # # # # # # # #
#               !!! WARNING !!!               #
#          This is a generated file!          #
# All changes made in this file will be lost! #
# # # # # # # # # # # # # # # # # # # # # # # #


class GetPreparedInlineMessage(TLObject):  # type: ignore
    """Obtain a prepared inline message generated by a mini app: invoked when handling web_app_send_prepared_message events


    Details:
        - Layer: ``223``
        - ID: ``857EBDB8``

    Parameters:
        bot (:obj:`InputUser <hydrogram.raw.base.InputUser>`):
            The bot that owns the mini app that emitted the web_app_send_prepared_message event

        id (``str``):
            The id from the web_app_send_prepared_message event

    Returns:
        :obj:`messages.PreparedInlineMessage <hydrogram.raw.base.messages.PreparedInlineMessage>`
    """

    __slots__: List[str] = ["bot", "id"]

    ID = 0x857ebdb8
    QUALNAME = "functions.messages.GetPreparedInlineMessage"

    def __init__(self, *, bot: "raw.base.InputUser", id: str) -> None:
        self.bot = bot  # InputUser
        self.id = id  # string

    @staticmethod
    def read(b: BytesIO, *args: Any) -> "GetPreparedInlineMessage":
        # No flags
        
        bot = TLObject.read(b)
        
        id = String.read(b)
        
        return GetPreparedInlineMessage(bot=bot, id=id)

    def write(self, *args) -> bytes:
        b = BytesIO()
        b.write(Int(self.ID, False))

        # No flags
        
        b.write(self.bot.write())
        
        b.write(String(self.id))
        
        return b.getvalue()
